- hosts: localhost
  become: true
  vars_prompt:
    - name: "my_user"
      prompt: "Enter user"
      private: false
    - name: "my_password"
      prompt: "Enter password"
      private: true
  tasks:
  - name: update ubuntu to latest
    apt: upgrade=dist update_cache=yes

  - name: Install more stuff
    apt:
      name:
        - linux-oem-22.04d
        - vim
        - curl
        - wget
        - tldr
  - name: update tldr
    ansible.builtin.git:
      repo: 'https://github.com/tldr-pages/tldr.git'
      depth: 1
      dest: '~/.local/share/tldr'

  - name: 'changing shell to zsh for user: {{ my_user }}'
    command: usermod --shell /bin/bash {{ my_user }}
    changed_when: false

  - name: 'Install oh my zsh for user: {{ my_user }}'
    become: true
    become_user: "{{ my_user }}"
    shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    changed_when: false

  - name: Install zsh autosuggestions
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  - name: update zshrc
    become: true
    become_user: "{{ my_user }}"
    replace:
      path: ~/.zshrc
      regexp: '\(git'
      replace: '(git zsh-autosuggestions command-not-found'
  